### ISSUE TITLE
Pytorch的版本？？

### ISSUE THREAD

**Issue by wzan0001** [Buzz-Beater/GEP_PAMI#1]
如题

**Comment by wzan0001** [comment]
能否有办法提供下数据集？cornell的网址已经停用了啊。

**Comment by Buzz-Beater** [comment]
The pytorch version we used is pytorch 1.0, but might as well work with current versions

**Comment by wzan0001** [comment]
Thank you for your reply and the download link!

**Comment by wzan0001** [comment]
hi, how to get the grammar_file '.pcfg'?  Run the grammar_gen.py?  But I don't know what file it represents.

**Comment by wzan0001** [comment]
hi, how to get the grammar_file '.pcfg'? Run the grammar_gen.py? But I don't know what the 'corpus' represents in line 18 ?

**Comment by Buzz-Beater** [comment]
I have added the needed grammar pcfg files in the sharing link. The general idea was using the action sequence to generate an nltk consistent grammar file, so you might as well try other methods for generating the grammar pcfg files. More details of this part are described in the paper.

**Comment by wzan0001** [comment]
what dose the duration_prior.json in gep_pred_topdown.py stand for?  it return mu and sigma. does it represent the average time and variance of each action?

**Comment by Buzz-Beater** [comment]
The gep_pred_topdown.py is the gep script for testing prediction (check in ```cad_pred.sh```). duration_prior basically covers mean and variance of the duration of each action, it should be stored as {act_name : [mean, variance]} after summarizing action statistics on your customized dataset.

**Comment by wzan0001** [comment]
thank you !
